#ifndef __ERR_CODES_H__
#define __ERR_CODES_H__

#define MAX_STR_LEN 100

#define SUCCESS 0
#define UNSUCCESSFUL_MEMORY_ALLOCATION -1
#define INCORRECT_CONTENT -2
#define INCORRECT_OPTION -3

#endif //__ERR_CODES_H__