#ifndef __ERR_CODES_H__
#define __ERR_CODES_H__

#define SUCCESS 0
#define INCORRECT_MENU_OPTION 1
#define INCORRECT_INPUT 2
#define UNSUCCESSFUL_MEMORY_ALLOCATION 3
#define STACK_OVERFLOW 4
#define PUSH_ERROR 5
#define EMPTY_VECTORS 6
#define EMPTY_LISTS 7
#define POP_ERROR 8

#endif